### ISSUE TITLE
Undefined is not an object on Client#studentInfo

### ISSUE THREAD

**Issue by vaporrrr** [EGGaming/studentvue.js#1]
Most likely specific to my school district, but I get `Unhandled promise rejection: TypeError: undefined is not an object`\`s while evaluating `xmlObjectData.StudentInfo[0].Address[0].CounselorName[0]`, `xmlObjectData.StudentInfo[0].Address[0].CounselorEmail[0]`, `xmlObjectData.StudentInfo[0].Address[0].CounselorStaffGU[0]`,  `xmlObjectData.StudentInfo[0].Address[0].HomeRoomTchEMail[0]`, `xmlObjectData.StudentInfo[0].Address[0].HomeRoomTch[0]`, and `xmlObjectData.StudentInfo[0].Address[0].HomeRoomTchStaffGU[0]` when calling method studentInfo() on Client. This is because my school district does not provide the information, making each of the arrays undefined (For example xmlObjectData.StudentInfo[0].Address[0].HomeRoomTchStaffGU is undefined)

There should be some sort of check for whether they are defined

**Comment by vaporrrr** [comment]
When someone else logged in 
`[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_a13.length')]
at node_modules/studentvue/lib/StudentVue/Client/Client.js:656:40 in processRequest.then$argument_0`
Not everyone has all the info filled out, in this case emergency contact, so undefined checks are needed

**Comment by listingclown3** [comment]
Hey vaporrr would you like to get in contact with me, I'd like to ask you a few questions about this API. I feel like you have more experience with TS and I thought you might be able to help me.

Discord: list3#8004

**Comment by EGGaming** [comment]
Okay I'll look into it. I didnt put these fields into consideration when I made this API during school. If you have any questions, add me on discord: specify_#8634
